spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:agripulse}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:agripulse}
    password: ${DB_PASSWORD:agripulse-dev}

  jpa:
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: false

  h2:
    console:
      enabled: false
